import { createBrowserRouter } from 'react-router-dom'
import { PublicLayout } from '@/components/layout/PublicLayout'
import { RouteErrorPage } from '@/pages/public/RouteErrorPage'
import { AdminAuthLayout } from '@/app/providers/AdminAuthLayout'
import { ProtectedRoute } from '@/app/router/ProtectedRoute'
import { AdminLayout } from '@/components/layout/admin/AdminLayout'
import {
  HomePage,
  NotFoundPage,
  ProgramsPage,
  ProgramDetailPage,
  VenuesPage,
  VenueDetailPage,
  SchedulesPage,
  InstructorsPage,
  AboutPage,
  ContactPage,
  GalleryPage,
  FaqPage,
  PrivacyPage,
  InscriptionPage,
  LoginPage,
  AdminDashboardPage,
  VenuesListPage,
  VenueFormPage,
  ProgramsListPage,
  ProgramFormPage,
  InstructorsListPage,
  InstructorFormPage,
  SchedulesListPage,
  ScheduleFormPage,
  AthletesListPage,
  AthleteFormPage,
  AthleteDetailPage,
  GuardiansListPage,
  GuardianFormPage,
  RegistrationsListPage,
} from '@/app/router/lazyPages'

export const router = createBrowserRouter([
  {
    path: '/',
    element: <PublicLayout />,
    errorElement: <RouteErrorPage />,
    children: [
      { index: true, element: <HomePage /> },
      { path: 'nosotros', element: <AboutPage /> },
      { path: 'programas', element: <ProgramsPage /> },
      { path: 'programas/:slug', element: <ProgramDetailPage /> },
      { path: 'sedes', element: <VenuesPage /> },
      { path: 'sedes/:slug', element: <VenueDetailPage /> },
      { path: 'horarios', element: <SchedulesPage /> },
      { path: 'instructores', element: <InstructorsPage /> },
      { path: 'galeria', element: <GalleryPage /> },
      { path: 'preguntas-frecuentes', element: <FaqPage /> },
      { path: 'inscripcion', element: <InscriptionPage /> },
      { path: 'contacto', element: <ContactPage /> },
      { path: 'privacidad', element: <PrivacyPage /> },
      { path: '*', element: <NotFoundPage /> },
    ],
  },
  {
    path: '/admin',
    element: <AdminAuthLayout />,
    errorElement: <RouteErrorPage />,
    children: [
      { path: 'login', element: <LoginPage /> },
      {
        element: <ProtectedRoute />,
        children: [
          {
            element: <AdminLayout />,
            children: [
              { index: true, element: <AdminDashboardPage /> },
              { path: 'sedes', element: <VenuesListPage /> },
              { path: 'sedes/nueva', element: <VenueFormPage /> },
              { path: 'sedes/:id/editar', element: <VenueFormPage /> },
              { path: 'programas', element: <ProgramsListPage /> },
              { path: 'programas/nuevo', element: <ProgramFormPage /> },
              { path: 'programas/:id/editar', element: <ProgramFormPage /> },
              { path: 'instructores', element: <InstructorsListPage /> },
              { path: 'instructores/nuevo', element: <InstructorFormPage /> },
              { path: 'instructores/:id/editar', element: <InstructorFormPage /> },
              { path: 'horarios', element: <SchedulesListPage /> },
              { path: 'horarios/nuevo', element: <ScheduleFormPage /> },
              { path: 'horarios/:id/editar', element: <ScheduleFormPage /> },
              { path: 'deportistas', element: <AthletesListPage /> },
              { path: 'deportistas/nuevo', element: <AthleteFormPage /> },
              { path: 'deportistas/:id', element: <AthleteDetailPage /> },
              { path: 'deportistas/:id/editar', element: <AthleteFormPage /> },
              { path: 'acudientes', element: <GuardiansListPage /> },
              { path: 'acudientes/nuevo', element: <GuardianFormPage /> },
              { path: 'acudientes/:id/editar', element: <GuardianFormPage /> },
              { path: 'inscripciones', element: <RegistrationsListPage /> },
            ],
          },
        ],
      },
    ],
  },
])
